[tool.poetry]
name = "library"
version = "0.1.10"
description = "Test libraries."
authors = ["Joel Gerber <joel@grrbrr.ca>"]
packages = [
    { include = "library" }
]

[tool.poetry.dependencies]
python = "^3.11"
robotframework = "^6.0.2"
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
